spring.datasource.url=${DATABASE_URI}
spring.datasource.username=${KNOWLEDGE_DATABASE_USER}
spring.datasource.password=${KNOWLEDGE_DATABASE_PASSWORD}

spring.sql.init.mode = never

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.exposed.generate-ddl = false

application.domain.url = https://knowledge.glitch.paris

spring.h2.console.enabled = false