server.port=8092

# System path will be used for storing images, docments, etc that may be added over time.
application.path.external = ${GLITCH_PATH}
application.api-key = "test"
application.use-mins = true

spring.application.name = knowledge
spring.web.resources.static-locations = classpath:/static,file:${application.path.external}/static
